name: Build and deploy .NET application to container app hellorazorcontainerapp

on:
  workflow_dispatch:

env:
  CONTAINER_APP_CONTAINER_NAME: hellorazorcontainerapp
  CONTAINER_APP_NAME: hellorazorcontainerapp
  CONTAINER_APP_RESOURCE_GROUP_NAME: GCResourceGroup1
  CONTAINER_REGISTRY_LOGIN_SERVER: gclynch.azurecr.io
  DOCKER_FILE_PATH: HelloRazorContainerApp/Dockerfile
  PROJECT_NAME_FOR_DOCKER: hellorazorcontainerapp
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: docker/login-action@v3
      with:
        registry: gclynch
        username: ${{secrets.AZURE_REGISTRY_USERNAME}}
        password: ${{secrets.AZURE_REGISTRY_PASSWORD}}
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/src
        acrName: gclynch
        containerAppName: ${{env.CONTAINER_APP_CONTAINER_NAME}}
        resourceGroup: ${{env.CONTAINER_APP_RESOURCE_GROUP_NAME}}
 